# Exploratory Data Analysis of Large-Scale Retail Transaction Data

### Using Univariate, Bivariate and Multivariate Statistical Techniques

## Project Overview

Exploratory Data Analysis (EDA) is a systematic process used to inspect, summarize,
visualize and understand a dataset before applying statistical or machine learning
models.

This project performs detailed exploratory data analysis on a large-scale retail
transaction dataset containing 100,000 records and 18 variables.

The analysis will focus on:

- Understanding the structure and characteristics of the dataset
- Identifying missing, duplicate and invalid values
- Performing data cleaning and preparation
- Conducting univariate, bivariate and multivariate analysis
- Detecting and interpreting outliers
- Measuring correlation between numerical variables
- Analyzing skewness and kurtosis
- Extracting meaningful business insights

### Tools and Libraries

- Python
- Pandas
- NumPy
- Matplotlib
- Seaborn

In [ ]:
#Importing the required libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
# Display configuration
pd.set_option('display.max_columns', None)
pd.set_option('display.float_format', '{:.2f}'.format)

print("Libraries imported successfully.")

Libraries imported successfully.

### Loading and Intial Exploration of dataset

In [ ]:
df = pd.read_csv("retail_large_dataset.csv")

In [7]:
# Showing the first five rows of the dataset 
df.head()

,customer_id,age,gender,city,state,customer_segment,order_id,order_date,product_category,product_subcategory,product_price,quantity,discount_percentage,final_price,payment_method,shipping_type,delivery_days,return_status
0,C10000,56,Male,Hyderabad,Telangana,New,O50000,2025-05-10,Health,Protein Powder,38658,3,7,107855.82,Debit Card,Standard,5,No
1,C10001,36,Male,Pune,Maharashtra,Premium,O50001,2023-11-27,Electronics,Smartphone,22462,4,20,71878.40,Cash on Delivery,Standard,4,Yes
2,C10002,20,Male,Kolkata,West Bengal,New,O50002,2025-02-08,Fashion,Women Dress,56601,2,27,82637.46,Credit Card,Standard,5,No
3,C10003,39,Female,Jaipur,Rajasthan,New,O50003,2024-04-19,Beauty,Perfume,26158,3,9,71411.34,UPI,Standard,3,No
4,C10004,20,Male,Chennai,Tamil Nadu,Premium,O50004,2024-10-08,Beauty,Shampoo,31240,1,6,29365.60,UPI,Standard,2,No

In [8]:
# Showing the last five rows of the dataset
df.tail()

,customer_id,age,gender,city,state,customer_segment,order_id,order_date,product_category,product_subcategory,product_price,quantity,discount_percentage,final_price,payment_method,shipping_type,delivery_days,return_status
99995,C109995,29,Female,Pune,Maharashtra,Regular,O149995,2024-06-11,Health,Supplements,49293,1,11,43870.77,Debit Card,Standard,9,No
99996,C109996,28,Male,Mumbai,Maharashtra,Premium,O149996,2024-04-27,Fashion,Men T-Shirt,5722,2,22,8926.32,Cash on Delivery,Express,1,No
99997,C109997,44,Female,Jaipur,Rajasthan,Premium,O149997,2024-04-14,Grocery,Snacks,6311,4,11,22467.16,Cash on Delivery,Express,9,No
99998,C109998,45,Male,Jaipur,Rajasthan,Premium,O149998,2024-09-08,Beauty,Shampoo,46888,1,28,33759.36,Debit Card,Standard,1,No
99999,C109999,19,Male,Kolkata,West Bengal,New,O149999,2025-11-15,Health,Supplements,37361,3,3,108720.51,Credit Card,Standard,2,No

In [9]:
# Checking the dimensions of the dataset 
df.shape

(100000, 18)

In [ ]:
# Displaying the number of rows and columns explicitly
print(f"Number of rows    : {df.shape[0]:,}")
print(f"Number of columns : {df.shape[1]}")

Number of rows    : 100,000
Number of columns : 18

In [ ]:
# Checking the column names in dataset
df.columns

Index(['customer_id', 'age', 'gender', 'city', 'state', 'customer_segment',
       'order_id', 'order_date', 'product_category', 'product_subcategory',
       'product_price', 'quantity', 'discount_percentage', 'final_price',
       'payment_method', 'shipping_type', 'delivery_days', 'return_status'],
      dtype='object')

In [12]:
# Showcasing column names in a reader friendly format
for i, column in enumerate(df.columns, start=1):
    print(f"{i}. {column}")

1. customer_id
2. age
3. gender
4. city
5. state
6. customer_segment
7. order_id
8. order_date
9. product_category
10. product_subcategory
11. product_price
12. quantity
13. discount_percentage
14. final_price
15. payment_method
16. shipping_type
17. delivery_days
18. return_status

In [ ]:
# Checking for essential information about dataset such as dtypes , non-null values , memory usage etc.
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   customer_id          100000 non-null  object
 1   age                  100000 non-null  int64
 2   gender               100000 non-null  object
 3   city                 100000 non-null  object
 4   state                100000 non-null  object
 5   customer_segment     100000 non-null  object
 6   order_id             100000 non-null  object
 7   order_date           100000 non-null  object
 8   product_category     100000 non-null  object
 9   product_subcategory  100000 non-null  object
 10  product_price        100000 non-null  int64
 11  quantity             100000 non-null  int64
 12  discount_percentage  100000 non-null  int64
 13  final_price          100000 non-null  float64
 14  payment_method       100000 non-null  object
 15  shipping_type        100000 non-null  object
 16  delivery_days        100000 non-null  int64
 17  return_status        100000 non-null  object
dtypes: float64(1), int64(5), object(12)
memory usage: 13.7+ MB

In [ ]:
# Counting the number of columns based on their data types
df.dtypes.value_counts()

object     12
int64       5
float64     1
Name: count, dtype: int64

In [18]:
# Summarizing the dataset to get a statistical overview of numerical columns 
df.describe()

,age,product_price,quantity,discount_percentage,final_price,delivery_days
count,100000.00,100000.00,100000.00,100000.00,100000.00,100000.00
mean,41.56,30164.53,2.50,15.01,64165.72,5.51
std,13.85,17139.68,1.12,8.95,49969.28,2.87
min,18.00,500.00,1.00,0.00,357.00,1.00
25%,30.00,15375.00,1.00,7.00,24705.00,3.00
50%,42.00,30148.00,3.00,15.00,49752.39,5.00
75%,54.00,44957.00,4.00,23.00,94046.07,8.00
max,65.00,59998.00,4.00,30.00,239980.00,10.00

In [ ]:
# Summarizing the categorical columns to get statistical overview 
df.describe(include='object')

,customer_id,gender,city,state,customer_segment,order_id,order_date,product_category,product_subcategory,payment_method,shipping_type,return_status
count,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000,100000
unique,100000,2,10,9,3,100000,1095,6,21,4,2,2
top,C10000,Male,Hyderabad,Maharashtra,New,O50000,2023-04-12,Health,Protein Powder,Credit Card,Express,No
freq,1,50111,10150,19952,33488,1,124,16858,5668,25307,50008,85189

In [20]:
# Checking for number of unique values in each column
df.nunique()

customer_id            100000
age                        48
gender                      2
city                       10
state                       9
customer_segment            3
order_id               100000
order_date               1095
product_category            6
product_subcategory        21
product_price           48449
quantity                    4
discount_percentage        31
final_price             97092
payment_method              4
shipping_type               2
delivery_days              10
return_status               2
dtype: int64

In [21]:
categorical_columns = df.select_dtypes(include='object').columns

for column in categorical_columns:
    print(f"\n{'='*50}")
    print(f"{column}")
    print(f"{'='*50}")
    print(df[column].unique())

==================================================
customer_id
==================================================
['C10000' 'C10001' 'C10002' ... 'C109997' 'C109998' 'C109999']

==================================================
gender
==================================================
['Male' 'Female']

==================================================
city
==================================================
['Hyderabad' 'Pune' 'Kolkata' 'Jaipur' 'Chennai' 'Delhi' 'Ahmedabad'
 'Noida' 'Mumbai' 'Bangalore']

==================================================
state
==================================================
['Telangana' 'Maharashtra' 'West Bengal' 'Rajasthan' 'Tamil Nadu' 'Delhi'
 'Gujarat' 'Uttar Pradesh' 'Karnataka']

==================================================
customer_segment
==================================================
['New' 'Premium' 'Regular']

==================================================
order_id
==================================================
['O50000' 'O50001' 'O50002' ... 'O149997' 'O149998' 'O149999']

==================================================
order_date
==================================================
['2025-05-10' '2023-11-27' '2025-02-08' ... '2024-03-08' '2023-07-25'
 '2023-06-03']

==================================================
product_category
==================================================
['Health' 'Electronics' 'Fashion' 'Beauty' 'Grocery' 'Home & Kitchen']

==================================================
product_subcategory
==================================================
['Protein Powder' 'Smartphone' 'Women Dress' 'Perfume' 'Shampoo' 'Pulses'
 'Headphones' 'Vitamins' 'Blender' 'Supplements' 'Snacks' 'Shoes'
 'Organic Rice' 'Laptop' 'Face Cream' 'Vacuum Cleaner' 'Men T-Shirt'
 'Jeans' 'Tablet' 'Cookware' 'Microwave']

==================================================
payment_method
==================================================
['Debit Card' 'Cash on Delivery' 'Credit Card' 'UPI']

==================================================
shipping_type
==================================================
['Standard' 'Express']

==================================================
return_status
==================================================
['No' 'Yes']

In [22]:
# Checking the date column explicitly to see if it is in the correct format
df['order_date'].head()

0    2025-05-10
1    2023-11-27
2    2025-02-08
3    2024-04-19
4    2024-10-08
Name: order_date, dtype: object

## Column Classification

### Identifier Variables
- customer_id
- order_id

### Numerical Variables
- age
- product_price
- quantity
- discount_percentage
- final_price
- delivery_days

### Categorical Variables
- gender
- city
- state
- customer_segment
- product_category
- product_subcategory
- payment_method
- shipping_type
- return_status

### Date Variable
- order_date

## Initial Observations

Based on the initial inspection of the dataset:

1. The dataset contains 100,000 transaction records and 18 variables.
2. The dataset includes identifier, numerical, categorical and date variables.
3. Customer and order identifiers should not be treated as conventional numerical features.
4. The numerical variables include age, product price, quantity, discount percentage,
   final price and delivery days.
5. The dataset contains categorical information related to customers, products,
   payment methods, shipping and returns.
6. The order date provides an opportunity for time-based analysis.
7. Further investigation is required to identify missing, duplicate, inconsistent
   and invalid values before performing detailed visualization.